name: Docker

on:
  push:
    paths:
      - 'Docker'
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/thisgary/hosting
  VERSION: ${GITHUB_REF/refs\/tags\//}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u thisgary --password-stdin
      
      - name: Move to /Docker directory
        run: cd Docker

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }} --all-tags
